version: 2
project_name: afdian-sponsor

release:
  prerelease: auto

builds:
  - id: afdian-sponsor
    main: ./
    binary: afdian-sponsor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    asmflags:
      - -trimpath
    gcflags:
      - all=-d=ssa/check_bce/debug=0
    ldflags:
      - -s -w -buildid=
      - -extldflags=-static
      - -linkmode internal
      - -X github.com/snltty/afdian-sponsor/version.version={{.Version}}
      - -X github.com/snltty/afdian-sponsor/version.commit={{.Commit}}
      - -X github.com/snltty/afdian-sponsor/version.date={{.Date}}

dockers_v2:
  - images:
      - "ghcr.io/snltty/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Generate afdian sponsors svg on github action"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: "^.*feat(?:\\([^)]+\\))?:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix(?:\\([^)]+\\))?:+.*$"
      order: 1
    - title: "⚡️ Performance Improvements"
      regexp: "^.*perf(?:\\([^)]+\\))?:+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs(?:\\([^)]+\\))?:+.*$"
      order: 3
    - title: "🔧 Maintenance & Chores"
      regexp: "^.*chore(?:\\([^)]+\\))?:+.*$"
      order: 4
    - title: "♻️ Code Refactoring"
      regexp: "^.*refactor(?:\\([^)]+\\))?:+.*$"
      order: 5
    - title: "🧪 Tests"
      regexp: "^.*test(?:\\([^)]+\\))?:+.*$"
      order: 6
    - title: "📦 Dependency Updates"
      regexp: "^.*deps(?:\\([^)]+\\))?:+.*$"
      order: 7
    - title: "📍 Others"
      order: 999
